name: Test and Tag

on:
  push:
    branches:
      - main  # or whatever your default branch is named

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    permissions: # Add this permissions block
      contents: write # This allows pushing tags
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for tagging
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'  # Specify your Go version
    
    - name: Run tests
      run: go test ./... -v
    
    - name: Generate tag
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN      
      run: |
        # Get current date for tag
        DATE=$(date +'%Y.%m.%d')
        # Get current count of tags for today to create unique tag
        COUNT=$(git tag | grep $DATE | wc -l)
        # Create new tag
        NEW_TAG="v$DATE.$COUNT"
        
        # Configure Git
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Create and push tag
        git tag $NEW_TAG
        git push origin $NEW_TAG
